### PR TITLE
Added "Top five universities"

### PR DESCRIPTION
**Pull request by killvung**

### CODE REVIEW

**Comment by alasdairhurst** [comment]
This should probably be worldwide rather than US specific if it does go in.

**Comment by killvung** [comment]
Senpai y u no pull request

**Comment by alasdairhurst** [comment]
Seems a bit too opinionated.  For example, a number of lists have Oxford as number 1, but that isn't in yours.

**Comment by killvung** [comment]
If you looked close, I pull the list based on the ranking site, choices are qs, arwu and college news.

However they rank the school are up to them

**Comment by killvung** [comment]
If you looked closed, I return the list based on the ranking site the clients want to use. 
Choices are arwu, qs and college news. 

However they rank the school are up to them. 

ARWU
http://www.shanghairanking.com/ARWU2016.html

QS
https://www.topuniversities.com/university-rankings/world-university-rankings/2018

College news 
https://www.usnews.com/best-colleges

**Comment by goosehub** [comment]
I agree with @alasdairhurst that this is too opinionated. Would this have to be updated every few years?

**Comment by killvung** [comment]
yea, that's why I closed and instead seeking for "static" idea

**Pull request closed without merging**
