### PR TITLE
Implementing five base N

### PR DESCRIPTION
**Pull request by antoligy**
It seems wholly unreasonably that we cannot get values of Five to a _given_ power!

### CODE REVIEW

**Comment by Joezo** [comment]
If you could update the readme i'll be happy to merge these

**Comment by antoligy** [comment]
Just done that :smile:

**Comment by antoligy** [comment]
Yo, any updates on this?

**Comment by Arditc** [comment]
There seems to be merge conflicts :-1:

**Comment by antoligy** [comment]
Just merged from upstream.

**Comment by Joezo** [comment]
Nice one :+1: thank you!

**Pull request merged**
