### PR TITLE
Add five.euro() and five.dollar //5€ a 5$

### PR DESCRIPTION
**Pull request by guifl**
Add five.euro() and five.dollar //5€ a 5$

### CODE REVIEW

**Comment by Joezo** [comment]
Can you add this to the readme please? I'm not used to seeing dollars expressed as `5$`, should it be `$5`?

**Comment by guifl** [comment]
I add it to the readme.
About the $ I don't know... I'm from a france so maybe it should be $5, I change it too

**Comment by Joezo** [comment]
Thanks for updating! I'm not sure what's happened to the readme though, you've put a heading of `Money` but under that the the emoji based representations of five. Perhaps give it another go? 
Thank you!

**Comment by guifl** [comment]
Done, sorry for the mistake

**Comment by Joezo** [comment]
Thanks @guifl :D

**Pull request merged**
