### PR TITLE
add pinyin and financial use for `five.chinese()`

### PR DESCRIPTION
**Pull request by Justineo**
See [Chinese numerals](http://en.wikipedia.org/wiki/Chinese_numerals#Standard_numbers).

### CODE REVIEW

**Comment by 599316527** [comment]
Cool! It's pretty fucking useful.

**Comment by Joezo** [comment]
This is smart, could you update the readme? :)

**Comment by Justineo** [comment]
@Joezo done.

**Comment by jodiedoubleday** [comment]
I know this has been a long time coming, but can you fix your merge conflicts and i'll try and get this merged

**Comment by Justineo** [comment]
Sorry, didn't see last comment until now. Everything's okay now.

**Comment by jackdcrawford** [comment]
Love this ❤️

**Pull request merged**
