### PR TITLE
Added "Interstella 5555: The 5tory of the 5ecret 5tar 5ystem"

### PR DESCRIPTION
**Pull request by YannickMG**
Fixed the glaring omission of Daft Punk's [Interstella 5555: The 5tory of the 5ecret 5tar 5ystem](https://en.wikipedia.org/wiki/Interstella_5555:_The_5tory_of_the_5ecret_5tar_5ystem)

### CODE REVIEW

**Comment by tOverney** [comment]
movies is quite non-descriptive and too generic, why wouldn't you call it `five.fiveFiveFive` or `five.daft` ?

**Comment by YannickMG** [comment]
Because I assume other movies will need to be added later on, so this would only be the first of the list.

Same as five.singles.

**Comment by Joezo** [comment]
I had the same thought as @tOverney and you're reply makes sense @YannickMG but unfortunately those are all singles by the band ['five'](https://www.google.co.uk/search?q=five+singles&oq=five+singles&aqs=chrome..69i57j0l5.1382j0j7&sourceid=chrome&ie=UTF-8) so i'm not sure it makes sense for this. I do LOVE the idea though, just think we can work on the method name.

**Comment by YannickMG** [comment]
I loved @tOverney's five.fiveFiveFive suggestion so I went with that.

**Comment by Joezo** [comment]
Fantastic! Love it :) Can you just add a quick test and i'll merge it?

**Comment by YannickMG** [comment]
Done.

**Comment by Joezo** [comment]
Thanks @YannickMG :D

**Comment by tOverney** [comment]
Nice job :)

**Pull request merged**
