### PR TITLE
Add South African Languages

### PR DESCRIPTION
**Pull request by Restioson**
This adds Afrikaans, isiZulu, and isiXhosa translations for 'five'. If anyone else speaks some of the more exotic south african languages such as Northern/Southern Sesotho, Tshivenda, Sepedi, Xitsonga, Setswana, etc. then please feel free to to submit a PR to my branch.

Also aliased isiZulu and isiXhosa to their colloquial names Xhosa and Zulu.

### CODE REVIEW

**Comment by goosehub** [comment]
This pull requests needs a test.

**Comment by Restioson** [comment]
@goosehub do you mean a test run or a unit test?

**Comment by goosehub** [comment]
@Restioson Every pull request needs a unit test in this file. https://github.com/jackdclark/five/blob/master/test.js

**Comment by Restioson** [comment]
I'll do that soon.

**Comment by Restioson** [comment]
OK I actually will now...

**Comment by goosehub** [comment]
The tests should return the output of the function being tested. For instance, for this function

`five.afrikaans = function() { return 'vyf'; };`

The test is currently

`assert.equal('afrikaans', five.afrikaans(), 'An afrikaans five should be vyf');`

But should be 

`assert.equal('vyf', five.afrikaans(), 'An afrikaans five should be vyf');`

Also, I don't think the person running this project has accepted any PRs in a long time, so might be a dead repo. Hope this helps you in writing future tests though!

**Comment by Restioson** [comment]
Ouch that was a typo there, did it on autopilot...

**Pull request closed without merging**
