### PR TITLE
Added the members, singles and discography of 5ive

### PR DESCRIPTION
**Pull request by ewanharris**
Does not solve the issue as discussed at #10 as it does not play music by 5ive. Can be added if needed. Was thinking five.play() which executes `exec('open "https://www.youtube.com/watch?v=qoPRDbC85NE"');` on Mac and prints the link on other platforms?

### CODE REVIEW

**Comment by TeriyakiCode** [comment]
This is a crucial addition.

**Comment by alasdairhurst** [comment]
I think this is very important.
@ewanharris please resolve conflicts
@jackdcrawford please merge

**Comment by jackdcrawford** [comment]
Sorry, I've dropped the ball on this one & that's my bad as it's a fundamental feature. If @ewanharris can resolve the conflicts I'll get this one merged. Thanks for picking this up.

**Comment by ewanharris** [comment]
Fancy changes to GitHub to resolve conflicts through the browser! @alasdairhurst @jackdcrawford should be updated now. Sorry for the time taken on this

**Comment by jackdcrawford** [comment]
No problem @ewanharris, worth the wait for a feature of this importance 🎉  

Thanks again for contributing!

:shipit:

**Pull request merged**
